### PR TITLE
[security] bump vm2 to 3.9.15

### PR DESCRIPTION
**Pull request by jeremypress**
appreciate you @TooTallNate , this package is supporting many things.

https://github.com/advisories/GHSA-7jxr-cg7f-gpgv

### CODE REVIEW

**Comment by jeremypress** [comment]
uh oh, I think I used pnpm8 here, let me fix up the lockfile

**Comment by jeremypress** [comment]
whew, that's better

**Comment by chanmo-kim** [comment]
@jeremypress 
plz vm2 to 3.9.16
https://github.com/patriksimek/vm2/security/advisories/GHSA-xj72-wvfv-8985

**Comment by jeremypress** [comment]
closing in favor of https://github.com/TooTallNate/node-degenerator/pull/23!

**Pull request closed without merging**
